# some settings
exclude: []  # list files here when need excluding
markdown: kramdown
highlighter: rouge
permalink: pretty
theme: lanyon

# Title/ base
name: Amy Andrews
baseurl: 'myndrws.github.io'

